name: Security Checks

on: [push, pull_request]

permissions: read-all

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Run SecChecks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install requirements
        run: |
          pip install checkov==2.2.220
          pip install detect-secrets==1.2.0
      - name: Detect Secrets
        run: |
          cp .secrets.baseline .secrets.new
          detect-secrets scan --baseline .secrets.new $(find . -type f ! -name '.secrets.*' ! -path '*/.git*')
          list_secrets() { jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort; }
          if ! diff <(list_secrets .secrets.baseline) <(list_secrets .secrets.new) >&2; then
            echo "Detected new secrets in the repo" >&2
            exit 1
          fi
      - name: Run Checkov
        run: checkov --skip-download --directory . --framework terraform
